# 1.1 Raw data profiling and split

Load the raw dataset, check its structure, then split train/test.

| Artifact | Path |
|---|---|
| Input | `1-experimentation/data/data_raw.csv` |
| Train | `1-experimentation/data/data_train.csv` |
| Test | `1-experimentation/data/data_test.csv` |

In [1]:
%pip install -q pandas scikit-learn

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 120)

RANDOM_STATE = 42
TEST_SIZE = 0.20

RAW_PATH = "../data/data_raw.csv"
TRAIN_PATH = "../data/data_train.csv"
TEST_PATH = "../data/data_test.csv"

## 1. Load raw data

In [3]:
df = pd.read_csv(RAW_PATH)

print(f"Rows: {df.shape[0]} | Columns: {df.shape[1]}")
df.head()

Rows: 86 | Columns: 7

       price  sqft  bedrooms  bathrooms    location  year_built  condition
0   495000.0  1527         2        1.5      Suburb        1956       Good
1   752000.0  2526         3        2.5    Downtown        1998  Excellent
2   319000.0  1622         2        1.5       Rural        1975       Fair
3  1210000.0  3102         4        3.0  Waterfront        2005  Excellent
4   462000.0  1835         2        2.0       Urban        1982       Good

## 2. Structural profile

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 86 entries, 0 to 85
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   price       85 non-null     float64
 1   sqft        86 non-null     int64
 2   bedrooms    86 non-null     int64
 3   bathrooms   86 non-null     float64
 4   location    86 non-null     str
 5   year_built  86 non-null     int64
 6   condition   86 non-null     str
dtypes: float64(2), int64(3), str(2)
memory usage: 4.8 KB

In [5]:
schema = pd.DataFrame({
    "dtype": df.dtypes.astype(str),
    "non_null": df.notna().sum(),
    "nulls": df.isna().sum(),
    "null_pct": (df.isna().mean() * 100).round(2),
    "n_unique": df.nunique(dropna=False),
})
schema

              dtype  non_null  nulls  null_pct  n_unique
price       float64        85      1      1.16        84
sqft          int64        86      0      0.00        68
bedrooms      int64        86      0      0.00         4
bathrooms   float64        86      0      0.00         8
location        str        86      0      0.00         6
year_built    int64        86      0      0.00        53
condition       str        86      0      0.00         4

In [6]:
print(f"Duplicate rows: {df.duplicated().sum()}")
print(f"Missing values: {int(df.isna().sum().sum())}")

Duplicate rows: 1
Missing values: 1

## 3. Train / test split

Split the raw table (features + target together), 80% train / 20% test, with a fixed `random_state`.

In [7]:
train_df, test_df = train_test_split(
    df,
    test_size=TEST_SIZE,
    random_state=RANDOM_STATE,
)

train_df = train_df.reset_index(drop=True)
test_df = test_df.reset_index(drop=True)

print(f"Train: {train_df.shape[0]} rows ({train_df.shape[0] / len(df):.0%})")
print(f"Test : {test_df.shape[0]} rows ({test_df.shape[0] / len(df):.0%})")

Train: 68 rows (79%)
Test : 18 rows (21%)

In [8]:
train_df.to_csv(TRAIN_PATH, index=False)
test_df.to_csv(TEST_PATH, index=False)

print("Saved train/test splits.")

Saved train/test splits.